server:
  port: 10001

spring:
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
  datasource:
    url: jdbc:mysql://1.117.245.105:3306/gulimail_pms
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


